# Generated by Django 5.0.6 on 2024-06-10 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('empleado_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_empleado', models.CharField(blank=True, max_length=50, null=True)),
                ('apellido_empleado', models.CharField(blank=True, max_length=50, null=True)),
                ('correo_empleado', models.CharField(blank=True, max_length=50, null=True)),
                ('password', models.CharField(max_length=150)),
                ('fecha_registro_empleado', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(default='1', max_length=50)),
            ],
        ),
    ]
