# Generated by Django 5.0.6 on 2024-06-03 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion_producto', models.CharField(blank=True, max_length=50, null=True)),
                ('precio_producto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_producto', models.IntegerField(blank=True, null=True)),
                ('fecha_creacion_producto', models.DateTimeField(auto_now_add=True)),
                ('imagen_producto', models.ImageField(upload_to='')),
                ('estado', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
