# Generated by Django 5.0.6 on 2024-06-03 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_producto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen_producto',
            field=models.ImageField(upload_to='productos_imagenes/'),
        ),
    ]
