# Generated by Django 5.0.6 on 2024-06-03 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_producto', '0002_alter_producto_imagen_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='descripcion_producto',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Descripcion del producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='fecha_creacion_producto',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de ingreso-producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen_producto',
            field=models.ImageField(upload_to='productos_imagenes/', verbose_name='Imagen del producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre_producto',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre del producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_producto',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio del producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock_producto',
            field=models.IntegerField(blank=True, null=True, verbose_name='Cantidad del producto'),
        ),
    ]
